### ISSUE TITLE
 -Dcucumber.installGems=true doesn't seem to install the gems properly

### ISSUE THREAD

**Issue by nilswloka** [cucumber-attic/cuke4duke#8]
I'm using cuke4duke with a setup similar to the Spring example. When trying to execute a specification, I get the following error:

```
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'cuke4duke'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Unnamed - XXXXXXXXXXX:jar:1.0
[INFO]    task-segment: [cuke4duke:features]
[INFO] ------------------------------------------------------------------------
[INFO] [cuke4duke:features]
[INFO] Error opening script file: C:/Entwicklung/Repositories/Maven2/.gem/bin/cucumber (Das System kann den angegebenen Pfad nicht finden)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Cucumber failed: Java returned: 1
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: Cucumber failed: Java returned: 1
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:580)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:513)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:483)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:331)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:292)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:301)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoFailureException: Cucumber failed: Java returned: 1
    at cuke4duke.mojo.CucumberMojo.execute(CucumberMojo.java:69)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:453)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
    ... 16 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Fri Aug 14 00:19:32 CEST 2009
[INFO] Final Memory: 4M/9M
[INFO] ------------------------------------------------------------------------`
```

As you can see, I have configured a custom Maven repository location. I am using JRuby 1.3.0 under Windows Vista (if it makes a difference).

Neither the .gem directory nor any subdirectories get created. Precreating .gem inside the Maven repository doesn't help.

**Comment by aslakhellesoy** [comment]
This should be fixed in cuke4duke 0.1.0. Can you try to upgrade?

**Comment by nilswloka** [comment]
It still doesn't create directories inside my repository nor downloads any artifacts. Creating .gem\bin manually and copying the cucumber script yielded limited success. After another Maven run, further subdirectories of .gem had been created, but no gems had been downloaded.

**Comment by nilswloka** [comment]
mvn --version output is:

Maven version: 2.0.10
Java version: 1.6.0_14
OS name: "windows vista" version: "6.0" arch: "x86" Family: "windows"

**Comment by darrinholst** [comment]
hmm, we just ran cuke4duke on a fresh windows install today and the only problem we had was due to the path to the repo having spaces in it. Are you behind a http proxy or anything? Can you run jruby -S gem install cucumber?

**Comment by aslakhellesoy** [comment]
Windows defaults user HOME directories to be under Documents and Settings, which is a path with spaces. Yet, Windows supports spaces in paths really poorly. Please make sure you don't have any spaces in your paths. It would be great not to have to fix Windows brokenness in cuke4duke.

**Comment by nilswloka** [comment]
I don't use the default path for my Maven repository and as stated above, cuke4duke does seem to do /something/ once I manually create the first directory. I'm willing to blame the observed behaviour on some Vista weirdness, though. When I find the time, I'll make sure to test cuke4duke under cygwin and with different Maven versions.

**Comment by aslakhellesoy** [comment]
It would be great if you could try it on a different OS than Vista. (I'm truly sorry you have to use that). I will probably never have access to Vista myself. I use XP when I use Windows, and will probably go for Windows 7 when I upgrade.

**Comment by aslakhellesoy** [comment]
springify,

Could you please try again and pass -X to maven? And put the whole output in a gist that you link to from here?

**Comment by aslakhellesoy** [comment]
Attribution to Torbjørn Vatn. Closed by 0bbe4265104afbce1067f705636554a53223fb3b

**Comment by nilswloka** [comment]
Do I need to upgrade to a different plugin version? Just in case you still need the output, it's here: http://gist.github.com/184554. Update: For some reason http://github.com/moserp/maven-cuke4duke-skeleton/tree/master works for me, btw.

**Comment by aslakhellesoy** [comment]
What plugin are you referring to? Did you cut off your gist at the end? I need the whole thing - more specifically the java command that is used to launch gem install....

Reopening this - I must have accidentally closed this.

**Comment by aslakhellesoy** [comment]
Hmm - this tracker doesn't let me reopen a ticket. Well, it's still "open"
